version: "3.9"

services:
  web:
    build:
      context: .
    ports:
      - "7000:80"
    volumes:
      - ./public:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: practise
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro


volumes:
  mysql_data:
